name = "meeting-sync-cron"
main = "cf-worker/index.ts"
compatibility_date = "2025-07-13"

[build]
upload = { format = "modules" }

[triggers]
crons = ["* * * * *"]

[vars]
CRON_SECRET = "dev-secret-value"

[env.production]
vars = { CRON_SECRET = "cron-secret-meeting-scheduling-software-engineering-course" }