name: Secure Cron Job Every Minute

on:
  schedule:
    - cron: '*/1 * * * *'
  workflow_dispatch:

jobs:
  trigger-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Send secured POST request to cron API
        run: |
          curl -X POST https://meeting-sync-beta.vercel.app/api/run-cron \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}"
